[package]
name = "ci"
version = "0.1.2"
edition = "2024"
description = "Scaffold and manage NestJS projects"

[[bin]]
name = "ci"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
atom-engine = "5.0.2"
clap = { version = "4.6.6", features = ["derive"] }
self_update = { version = "0.44.0", default-features = false, features = ["reqwest", "rustls", "archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
